### ISSUE TITLE
Allow for ability to POST json data instead of long endpoint URL

### ISSUE THREAD

**Issue by maxmarchuk** [MrRacoon/home-control-server#1]
Right now the server can change lighting if a user hits a certain endpoint (e.g. /lighting/change/{hue}/{saturation}/{luminecence}/{white}/{fade-time}) which is kind of a long URL. It'd be nice to be able to just post a json object with the attributes to certain endpoints
e.g. post to /lighting/change/  some json {"hue":"red", "saturation": "0xFFFF", ....}.

**Comment by MrRacoon** [comment]
Good timing! I just finished writing it!

**Comment by MrRacoon** [comment]
Pushed
